exe-name := 'z.out'

default: build test-cli
    nix run

test-cli:
    ./result/bin/{{exe-name}} --help
    ./result/bin/{{exe-name}} -n 8
    ./result/bin/{{exe-name}} --number 64
    ./result/bin/{{exe-name}} --number 64 -s string_cheese

# open editor in a dev shell
edit:
    nix develop --command bash -c "nvim"

# drop into dev shell
dev:
    nix develop --command fish

# build & test
build: 
    nix build
