jd := justfile_directory()

# list recipes
default:
    @just --list

test:
    nix develop --command bash -c "zig build test"

run:
    nix run

edit:
    nix develop --command bash -c "nvim"

develop:
    nix develop --command fish

build: 
    nix build

clean:
    rm -rf zig-out
    rm -rf .zig-cache
