alias b := build
alias d := develop

jd := justfile_directory()
bin_dir := jd / "result" / "bin"

# calls run
default: && run
    git add .

# run `nix build`
build: 
    nix build

# open nix flake shell
develop:
    nix develop

edit:
    nix develop --command bash -c "nvim"

# run main.py
run:
    nix run
