jd := justfile_directory()

# list recipes
default:
    @just --list

# drop into dev shell
develop:
    nix develop

# run main.R
run:
    nix develop --command bash -c "Rscript main.R"

# drop into dev shell and launch neovim
edit:
    nix develop --command bash -c "nvim"
