alias b := dev-build
alias d := develop
alias r := run
jd := justfile_directory()

# list recipes
default:
    @just --list

# drop into dev shell
develop:
    nix develop --command ghostty

build:
    nix build

run:
    nix run

dev-build:
    alejandra .
    nix build
